### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by nullxx** [nullxx/ms#2]
- [x] #6
- [x] #9
- [x] #10
- [x] #11
- [x] Falta el +1 que se vea bien. #11
- [x] #3
- [x] #4
- [x] #7
- [x] Poner el bus arriba del todo. --> #10
- [x] Poner líneas de datos, que quede claro con las líneas de control. --> #10
- [x] Quién se va a ejecutar, que quede claro, que está preparado para cuando llegue el flanco. --> #10
- [x] Tener líneas de control aparte con el valor del siguiente ciclo. --> #10
- [ ] Hacer clock para adelante y para atrás.
- [x] #8
- [x] #5

La web <a href="https://ms.nullx.me" target="_blank">ms.nullx.me</a> está **actualizada** a la última, conteniendo las tareas completadas
